version: '3'
services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=user
      - N8N_BASIC_AUTH_PASSWORD=user@123
      - N8N_HOST=192.xx.xx.xx
      - N8N_PORT=5678
      - N8N_SECURE_COOKIE=false
      - N8N_PAYLOAD_SIZE_MAX=100
    volumes:
      - n8n_data:/home/node/.n8n
volumes:
  n8n_data:
